name: ClientTest

on: 
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep 
      - dev

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Install dependencies and CSS
        run: cd client && npm install --legacy-peer-deps && npx tailwindcss -i ./src/index.css -o ./src/dist/output.css

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          start: npm start
          wait-on: 'http://localhost:3000' 
          wait-on-timeout: 60 


