name: ClientTest
on: 
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep 

jobs:
  Firefox:
    runs-on: ubuntu-latest
    # container:
    #   image: cypress/browsers:node16.14.2-slim-chrome103-ff102
    #   options: --user 1001
    steps:
      # - name: Waiting Heroku Deployment
      #   uses: juliangruber/sleep-action@v2.0.0
      #   with:
      #     time: 45s

      # - uses: actions/checkout@v2
      # - name: Run against 
      #   uses: cypress-io/github-action@v4
      #   with:
      #     working-directory: client
      #     browser: firefox
      #   env: 
      #     NPM_CONFIG_PRODUCTION: false
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (client)
        working-directory: client
        run: npm install

      - name: Run tests (client)
        working-directory: client
        run: npx cypress run
#           # CYPRESS_TEST_USER_EMAIL: "cypress@example.com"
#           # CYPRESS_TEST_USER_PASS: ${{ secrets.CYPRESS_TEST_USER_PASS }}
#           # CYPRESS_baseUrl: ${{ github.event.deployment_status.environment_url }}
