name: ClientTest

on: 
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep 

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set ENV vars to test
        run: | 
          echo "NODE_ENV=test" >> $GITHUB_ENV
          echo "URI=${{ secrets.URI }}" >> $GITHUB_ENV 
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Start server
        working-directory: server
        run: nohup npm start &

      - name: Start client
        working-directory: client
        run: nohup npm start &

      - name: Wait for server and client to be responsive
        run: npx wait-on http://localhost:4000 http://localhost:3000

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60 