name: ClientTest

on: 
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep 

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Install dependencies
        run: cd client && npm install
      
      - name: Start server
        run: ../cd server && node server.js
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          start: npm start
          wait-on: 'http://localhost:3000' 
          wait-on-timeout: 60 


