name: ClientTest

on: 
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep 
      - dev
      - jason_front
      - jaden

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Install dependencies
        run: cd client && npm install --legacy-peer-deps

      - name: Install CSS
        run: npx tailwindcss -i ./client/src/index.css -o ./client/src/dist/output.css

      - name: Install server
        run: cd server && npm install --legacy-peer-deps

      - name: Start server
        run: |
          cd server
          npm start &

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          start: npm start
          install: false
          wait-on: 'http://localhost:3000' 
          wait-on-timeout: 60
         

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
            name: clientcypress-screenshots
            path: client/cypress/screenshots