name: ClientTest

on: 
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep 

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Start server in the background
        working-directory: server
        run: nohup npm start &

      - name: Wait for server to be responsive
        run: npx wait-on http://localhost:3000

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          start: ''
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60