name: Continuous Deployment

on:
  push:
    branches:
      - main
      - kahui
      - raymondlui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy to Staging on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'test-cypress-geowizard'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
      - name: Docker Login to E2E Testing App
        run:
          docker login --username=_ --password=${{secrets.HEROKU_API_KEY}}
          registry.heroku.com
      - name: Run E2E testing on Staging
        run: docker run registry.heroku.com/test-cypress-geowizard/web
    # - name: Deploy to production
    # etc
