name: ClientTest

on: 
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep 

jobs:
  Cypress:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome103-ff102
      options: --user 1001

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (client)
        working-directory: client
        run: npm install

      - name: Run Cypress tests (client)
        working-directory: client
        run: npx cypress run
