name: Continuous Deployment

on:
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploying Test Case Container
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'test-cypress-geowizard'
          email: ${{secrets.HEROKU_EMAIL}}

      - name: Docker Login to E2E Testing App
        run:
          docker login --username=_ --password=${{secrets.HEROKU_API_KEY}}
          registry.heroku.com
      - name: Run E2E testing on Staging
        run: docker run registry.heroku.com/test-cypress-geowizard/web
    # - name: Deploy to production
    # etc
