name: ClientTest

on: 
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep 

jobs:
  Cypress:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome103-ff102
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (client)
        working-directory: client
        run: npm install

      - name: Start server
        working-directory: client
        run: npm start &
        env:
          CI: true

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          start: npx cypress run
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60 # waits for 1 minute for the server to start

