name: Test with Multiple Node Versions

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - '14'
          - '16'
          - '18'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (root)
        run: npm install

      - name: Install dependencies (server)
        working-directory: server
        run: npm install

      - name: Run tests (server)
        working-directory: server
        run: npm test
