name: ServerTest
on: 
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep 
    deployment_status:
      types:
        - success

jobs:
  Server:
    # if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Waiting Heroku Deployment
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 45s
      
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Run Test 
          with:
            working-directory: server
      - run : npm install
      - run : npm test 

