name: ServerTest

on:
  push:
    branches:
      - main
      - kahui
      - raymondlui
      - jason_dep

jobs:
  Server:
    runs-on: ubuntu-latest

    steps:
      - name: Waiting Heroku Deployment
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 45s

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Test
        working-directory: server
        run: npm install
        run: npm test