name: Test with Node.js 16

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies (root)
        run: npm install

      - name: Install dependencies (client)
        working-directory: client
        run: npm install

      - name: Install dependencies (server)
        working-directory: server
        run: npm install

      - name: Start the client
        working-directory: client
        run: npm start

      - name: Wait for the application to start
        working-directory: client
        run: npx wait-on --timeout 60000 http://localhost:3000

      - name: Run tests (client)
        working-directory: client
        run: npm run cypress:run

      - name: Run tests (server)
        working-directory: server
        run: npm test
